version: "3"
services:
  web:
    build: ./web
    image: cluster-web
    ports:
      - 3000:3000
    restart: on-failure
    links:
      - api
    depends_on:
      - api
    environment:
      PORT: "3000"
  api:
    build: ./api
    image: cluster-api
    ports:
      - 3001:3001
    restart: on-failure
    environment:
      PORT: "3001"