version: '3'
services:
  web:
    build: ../web
    ports:
      - '3000:3000'
    restart: on-failure
    links:
      - people_api
      - locations_api
    depends_on:
      - people_api
      - locations_api
    environment:
      PORT: '3000'
      NOW_HOST_PEOPLE_API: host.docker.internal
      NOW_PORT_PEOPLE_API: '3001'
      NOW_HOST_LOCATIONS_API: host.docker.internal
      NOW_PORT_LOCATIONS_API: '3002'
  people_api:
    build: ../people_api
    ports:
      - '3001:3001'
    restart: on-failure
    environment:
      PORT: '3001'
  locations_api:
    build: ../locations_api
    ports:
      - '3002:3002'
    restart: on-failure
    environment:
      PORT: '3002'
